#!/usr/bin/env python3

import argparse

parser = argparse.ArgumentParser(description="Adds content to a file of choice")

parser.add_argument('filename', help="Enter filename to add content to")
#parser.add_argument('-c', '--content', help="Content to Save to file")

args = parser.parse_args()

print(f"Please enter your content. Entering a empty line will write the content to file: {args.filename}\n")

with open(args.filename, 'w') as f:
    eof = False
    lines = []

    while not eof:
        line = input()
        if line.strip():
            lines.append(f"{line}\n")
        else:
            eof = True

    f.writelines(lines)
    print(f"Lines written to: {args.filename}")
