#!/usr/bin/env python3

#######################################################
## Written By: Shawn Oseguera Goetz                  ##
## Written On: 12/21/19                              ##
## Subject: Learning Python 3 - Positional Arguments ##
#######################################################

import sys

print(f"Positional Argument: {sys.argv[1:]}")
print(f"First Arguement: {sys.argv[1]}")
