#!/usr/bin/env python3

import argparse

## Initiate the parser object ##
parser = argparse.ArgumentParser(description='Read a file in reverse')

## Add arguments to the parser ##
parser.add_argument('filename', help='The File To Read')
parser.add_argument('-l', '--limit', type=int, help='The number of lines to read')
parser.add_argument('-v', '--version', action='version', version='%(prog)s 1.0')

## Parse the arguments given on the CLI ##
args = parser.parse_args()

try:
    f = open(args.filename)
except FileNotFoundError as err:
    print(f"Error: {err}")
else:
    with f:
        lines = f.readlines()
        lines.reverse()

        if args.limit:
            lines = lines[:args.limit]

        for line in lines:
            print(line.strip()[::-1])
