#!/usr/bin/env python3

##
## Demostrates use of os.getenv
## Can get environment Variable and if missing give default instead.
## ** Most Preferred way of doing this
###


import os

stage = os.getenv("STAGE", default="dev").upper()

output = f"We're running in {stage}"

if stage.startswith('PROD'):
    output = "DANGER!!! - " + output

print(output)
